# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

# [[main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 20

[[main]]
  name = "Use Cases"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  identifier = "publications"
  weight = 40

[[main]]
  name = "Featured Publications"
  url = "#featured"
  parent = "publications"
  weight = 410

[[main]]
  name = "All Publications"
  url = "/publication"
  parent = "publications"
  weight = 420

[[main]]
  name = "IETF"
  url = "#rfcs"
  weight = 50

[[main]]
  name = "Members"
  url = "#people"
  weight = 60

[[main]]
  name = "Demo"
  url = "/demo"
  weight = 70

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

[[main]]
  name = "Subscribe"
  url = "https://forms.gle/dUe2bd8zziQr5Zzf7"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
